language: php

php:
  - 7.1
  - 7.2

dist: trusty
sudo: required

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script: ./codeclimate.sh
