language: php

php:
  - 7.1
  - 7.2
  - 7.3

dist: trusty
sudo: required

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit

after_script: ./codeclimate.sh
