language: php

php:
  - 7.0
  - 7.1

dist: trusty
sudo: required

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script: php vendor/bin/coveralls
