name: CI

on: [push]

jobs:
  build-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show actual PHP version
      run: php -v
    - name: Install composer dependencies
      run: composer install --prefer-dist
    - name: Run tests
      run: php vendor/bin/phpunit